services:
  api:
    build: ./api
    ports:
      - "8080:8000"
    restart: unless-stopped

  hello:
    build: ./lab1
    ports:
      - "8081:80"
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.17.0
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlruns
    volumes:
      - ./_infra/mlflow/mlruns:/mlruns
      - ./_infra/mlflow/db:/mlflowdb
    ports:
      - "5000:5000"
    restart: unless-stopped
